### ISSUE TITLE
alg is None in the headers when using pyjwkest==1.0.8

### ISSUE THREAD

**Issue by fgaudin** [juanifioren/django-oidc-provider#65] opened 2015-12-03 00:26 UTC
I think this commit broke it: https://github.com/rohe/pyjwkest/commit/3292070ff3bf3e1a4ca5915832d7cbf9c121a006

I wonder if it's a bug in pyjwkest or something which can be fixed in oidc provider.

**Comment by fgaudin** [comment] 2015-12-03 00:33
Just seen your fix in the tests. Unless I'm wrong, it's not good to allow None in the tests. It skips the signature verification, allowing anyone to forge a token.

**Comment by fgaudin** [comment] 2015-12-03 00:37
created an issue on pyjwkest https://github.com/rohe/pyjwkest/issues/46

**Comment by juanifioren** [comment] 2015-12-03 03:51
Yup! Just decide to skip signature check so tests pass. Need to understand in deep why this happens, if the problem is here or in pyjwkest. I'll follow that issue.

**Comment by fgaudin** [comment] 2015-12-03 06:14
I would suggest to revert the tests and set the dependency to pyjwkest<=1.0.6 until a fix is found. With 1.0.8, the headers always contains alg: None which should indeed be considered wrong and rejected otherwise anyone can forge a JWT since the signature is not verified.

**Comment by juanifioren** [comment] 2015-12-03 16:31
You are right @fgaudin. Reverted.

**Comment by juanifioren** [comment] 2016-02-02 20:36
See https://github.com/juanifioren/django-oidc-provider/issues/76

**Comment by juanifioren** [comment] 2016-02-04 03:40
Since now we update pyjwkest to version `1.1.0` I'll close this.

**Closed by juanifioren** 2016-02-04 03:40 UTC
Labels: bug, dependencies
