### ISSUE TITLE
id_token doesn't include claims

### ISSUE THREAD

**Issue by dhrp** [juanifioren/django-oidc-provider#214] opened 2017-11-28 10:12 UTC
I've spent significant time on this and am now pretty sure there is an error causing no additional claims to be returned in the JWT when additional scopes (e.g. email, profile) are requested. 

Steps to reproduce (authorization code flow):

Requests authorization code with scopes 'idtoken email profile'

Use the code, client_id and client_secret with the same scopes to fetch the access token, id_token and refresh token.

Notice that in the resulting id_token there is no claims for email_verified, name or the like. 

I thought this was because I was using the OIDC_USERINFO setting wrong, but when the /token endpoint is hit this setting is never fetched and the respective function never called. 

My particular use-case is that I want to use OpenID Connect to connect to Kubernetes with the oidc authentication method. The Kubernetes API server checks for the email-verified claim in the id_token and errors if it is not found.

**Comment by dhrp** [comment] 2017-11-28 10:14
I've added a PR illustrating the issue in a test.

**Comment by wojtek-fliposports** [comment] 2017-11-28 11:43
Once again I must close this request. As is written here: http://openid.net/specs/openid-connect-core-1_0.html#IDToken and here http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

Basically, claims: "_They can be requested to be returned either in the UserInfo Response, per Section 5.3.2, or in the ID Token, per Section 2._ "  and in section 2: _"ID Tokens MAY contain other Claims. "_

and definition of MAY: 

> 5. MAY   This word, or the adjective "OPTIONAL", mean that an item is
>    truly optional.  

So this is not a bug but potentially enhancement. If you like, I'm open for PR to add this feature.

**Comment by dhrp** [comment] 2017-12-14 17:23
ok. I've contributed a PR. See. #220. I've tried to make it light and straightforward.

**Comment by juanifioren** [comment] 2018-04-10 21:46
Already merged on `develop`. Next version will contains this feature. Thanks for reporting and colaborate @dhrp .

http://django-oidc-provider.readthedocs.io/en/develop/sections/settings.html#oidc-idtoken-include-claims

**Closed by juanifioren** 2018-04-10 21:46 UTC
Labels: enhancement
